db.system.js.save({_id:"constant",value:function () {
        return {
                ADD:"ADD",
                ALL:"ALL",
                CATEGORY:"CATEGORY",
                CACHE:"CACHE",
				CURRENT_URL:"CURRENT_URL",
				CURRENT_MODULE:"CURRENT_MODULE",
                DELETE:"DELETE",
				EDIT:"EDIT",
				FAVORITE:"FAVORITE",
				ID:"ID",
				IS_NEW:"IS_NEW",
				IS_EDIT:"IS_EDIT",
				IS_DELETE:"IS_DELETE",
				IS_CATEGORY:"IS_CATEGORY",
				LOGIN:"LOGIN",
				LOGIN_TIME:"LOGIN_TIME",
				PASSWORD:"PASSWORD",
				USER_NAME:"USER_NAME",
				MODULE_NAME:"MODULE_NAME",
				MODULE_URL:"MODULE_URL",
				MODULE_LIST:"MODULE_LIST",
				MODULE_URL_LIST:"MODULE_URL_LIST",
				OK:"OK",
				ROLE_NAME:"ROLE_NAME",
				REMOTE_ADDRESS:"REMOTE_ADDRESS",
				SITE_NAME:"SITE_NAME",
				STORED_METHOD:"stored_method",
                TITLE:"TITLE",
                UPDATE_TIME:"UPDATE_TIME",
				USER_AGENT:"USER_AGENT",
				REFER:"REFER"
        };
}})

